Dev/2.0 q work
hms-networks/flexy-thingworx-connector pull request #51
Opened 2021-05-25 13:42 UTC by alexjhawk

2021-05-25 13:43 UTC, alexjhawk commented
Hold off on the review for a couple of minutes. I thought I ran code formatting, but it appears I missed that.

2021-05-25 14:03 UTC, alexjhawk commented
> Hold off on the review for a couple of minutes. I thought I ran code formatting, but it appears I missed that.

Corrected and now ready for review. Google's IDE plugin for google java format does not seem to catch all formatting issues now.

2021-05-25 14:09 UTC, oliver-walker-hms submitted a review, later dismissed

2021-05-25 14:49 UTC, TomKimsey requested changes
Why is there no build check being run?

2021-05-25 14:56 UTC, alexjhawk commented
> Why is there no build check being run?

Fixed - branch name was not correct in the action config

2021-05-25 14:56 UTC, alexjhawk commented on src/com/hms_networks/americas/sc/thingworx/data/TWApiManager.java
> +                boolean successful = sendJsonToThingworx(dataPayload.getPayloadString());
changed

2021-05-25 14:56 UTC, alexjhawk commented on src/com/hms_networks/americas/sc/thingworx/TWApiManager.java
> +    boolean successful = true;
changed

2021-05-26 13:45 UTC, oliver-walker-hms approved these changes

2021-05-26 13:54 UTC, TomKimsey approved these changes

2021-05-26 13:54 UTC, merged